### ISSUE TITLE
Utilise google maps API for aerial data

### ISSUE THREAD

**Issue by 1Solon** [2024-CMPU9010-GROUP-3/PROJECT#26]

**Comment by ankraus** [comment]
If this is going to be the main source of data for our project, we should make sure this approach complies with the Google Maps TOS.

![Image](https://github.com/user-attachments/assets/cda464df-11a1-49d1-bc85-2f55e0e0366e)
Source: https://www.google.com/help/terms_maps/

![Image](https://github.com/user-attachments/assets/ea05df61-1380-44d9-b7a9-34acb85e5f1b)
Source: https://cloud.google.com/maps-platform/terms/

I believe there are ways to do this without breaking the TOS (https://developers.google.com/earth-engine/guides/machine-learning), but I am unsure how financially viable it is compared to other aerial image providers.
I'm not saying the idea is inherently bad, I just really don't want to jeopardise our master's project because of legal issues.

**Comment by 1Solon** [comment]
Thanks for pointing this out @ankraus, these are reasonable concerns. We should look at the APIs and TOS of the various mapping providers.

I think when we get to this phase of development, we should probably take a look at [mapbox](https://docs.mapbox.com/api/maps/static-images/#static-images-api-pricing) 

If none of the providers, nor Mapbox work, we could also look into purchasing the data or requesting it from a public body

**Comment by nanadess** [comment]
I believe we can close this issue as well @ankraus
